server:
  port: 1001

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.qianjin.provider
  protocol:
    name: dubbo
    port: 20880