server:
  port: 8088

spring:
  cloud:
    gateway:
      routes:
        - id: gateway-service
          predicates:
            - Path=/gateway/** #路径匹配
          filters:
            - StripPrefix=1 #跳过前缀
          uri: lb://gateway-service #gateway-service的访问地址 lb://${spring.application.name}表示从注册中心获取地址，也支持普通URI
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gateway